const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    // Generate embedded frontend if assets exist
    generateEmbeddedFrontend(b) catch |err| {
        std.debug.print("Warning: Failed to generate embedded frontend: {any}\n", .{err});
    };

    // Add Zap dependency
    // ... (rest of the build function remains the same, adjusted for the new call)
    const zap_mod = b.dependency("zap", .{
        .target = target,
        .optimize = optimize,
    });
    const shfs_mod = b.dependency("StaticHttpFileServer", .{
        .target = target,
        .optimize = optimize,
    });
    const mime_mod = b.dependency("mime", .{
        .target = target,
        .optimize = optimize,
    });

    // Main server executable
    const root_mod = b.addModule("root", .{ .root_source_file = b.path("src/main.zig") });
    root_mod.addImport("zap", zap_mod.module("zap"));
    root_mod.addImport("StaticHttpFileServer", shfs_mod.module("StaticHttpFileServer"));
    root_mod.addImport("mime", mime_mod.module("mime"));
    root_mod.resolved_target = target;
    root_mod.optimize = optimize;

    const exe = b.addExecutable(.{
        .name = "selfhost-server",
        .root_module = root_mod,
    });

    // Link against SQLite and system libraries
    exe.linkLibrary(zap_mod.artifact("facil.io"));
    exe.linkSystemLibrary("sqlite3");
    exe.linkLibC();
    exe.linkLibCpp(); // Zap may need C++

    // Install executable
    b.installArtifact(exe);

    // Run executable
    const run_cmd = b.addRunArtifact(exe);
    run_cmd.step.dependOn(b.getInstallStep());

    if (b.args) |args| {
        run_cmd.addArgs(args);
    }

    const run_step = b.step("run", "Run the server");
    run_step.dependOn(&run_cmd.step);

    // Test step
    const test_root = b.addModule("root_test", .{ .root_source_file = b.path("src/main.zig") });
    test_root.addImport("zap", zap_mod.module("zap"));
    test_root.resolved_target = target;
    test_root.optimize = optimize;
    const unit_tests = b.addTest(.{
        .root_module = test_root,
    });
    unit_tests.linkLibrary(zap_mod.artifact("facil.io"));
    unit_tests.linkSystemLibrary("sqlite3");
    unit_tests.linkLibC();
    unit_tests.linkLibCpp();

    const run_unit_tests = b.addRunArtifact(unit_tests);
    const test_step = b.step("test", "Run unit tests");
    test_step.dependOn(&run_unit_tests.step);
}

fn generateEmbeddedFrontend(b: *std.Build) !void {
    const frontend_src = "../frontend/build";
    const frontend_dest = "src/frontend-embed";
    const output_file = "src/frontend_data.zig";

    var src_dir = std.fs.cwd().openDir(frontend_src, .{ .iterate = true }) catch |err| {
        if (err == error.FileNotFound) return;
        return err;
    };
    defer src_dir.close();

    // Ensure destination directory exists and is clean
    std.fs.cwd().deleteTree(frontend_dest) catch {};
    try std.fs.cwd().makePath(frontend_dest);
    var dest_dir = try std.fs.cwd().openDir(frontend_dest, .{});
    defer dest_dir.close();

    var out_file = try std.fs.cwd().createFile(output_file, .{});
    defer out_file.close();

    try out_file.writeAll("// This file is generated by build.zig. Do not edit manually.\n");
    try out_file.writeAll("const std = @import(\"std\");\n");
    try out_file.writeAll("const StaticHttpFileServer = @import(\"StaticHttpFileServer\");\n\n");
    try out_file.writeAll("pub fn populate(server: *StaticHttpFileServer, allocator: std.mem.Allocator) !void {\n");

    var walker = try src_dir.walk(b.allocator);
    defer walker.deinit();

    while (try walker.next()) |entry| {
        if (entry.kind == .file) {
            // Copy file to destination for embedding
            if (std.fs.path.dirname(entry.path)) |parent| {
                try dest_dir.makePath(parent);
            }
            try src_dir.copyFile(entry.path, dest_dir, entry.path, .{});

            const rel_path = try b.allocator.dupe(u8, entry.path);
            defer b.allocator.free(rel_path);
            for (rel_path) |*c| if (c.* == '\\') {
                c.* = '/';
            };

            var line_buf: [1024]u8 = undefined;
            const line = try std.fmt.bufPrint(&line_buf, "    try addFile(server, allocator, \"/{s}\", @embedFile(\"frontend-embed/{s}\"));\n", .{ rel_path, rel_path });
            try out_file.writeAll(line);
        }
    }

    try out_file.writeAll("}\n\n");
    try out_file.writeAll("fn addFile(server: *StaticHttpFileServer, allocator: std.mem.Allocator, path: []const u8, contents: []const u8) !void {\n");
    try out_file.writeAll("    const name_start = server.bytes.items.len;\n");
    try out_file.writeAll("    try server.bytes.appendSlice(allocator, path);\n");
    try out_file.writeAll("    const contents_start = server.bytes.items.len;\n");
    try out_file.writeAll("    try server.bytes.appendSlice(allocator, contents);\n");
    try out_file.writeAll("    const ext = std.fs.path.extension(path);\n");
    try out_file.writeAll("    const mime = @import(\"mime\");\n");
    try out_file.writeAll("    const mime_type = mime.extension_map.get(ext) orelse .@\"application/octet-stream\";\n");
    try out_file.writeAll("    try server.files.putContext(allocator, .{\n");
    try out_file.writeAll("        .mime_type = mime_type,\n");
    try out_file.writeAll("        .name_start = name_start,\n");
    try out_file.writeAll("        .name_len = @intCast(path.len),\n");
    try out_file.writeAll("        .contents_start = contents_start,\n");
    try out_file.writeAll("        .contents_len = contents.len,\n");
    try out_file.writeAll("    }, {}, StaticHttpFileServer.FileNameContext{ .bytes = server.bytes.items });\n");
    try out_file.writeAll("}\n");
}
